# @package _global_
name: ResNet34
arch:
  _target_: srcs.model.model.ResNet34
  num_classes: 25
loss:
  _target_: srcs.model.loss.cross_entropy
optimizer:
  _target_: torch.optim.Adam
  lr: ${learning_rate}
  weight_decay: ${weight_decay}
  amsgrad: true
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: ${scheduler_step_size}
  gamma: ${scheduler_gamma}
